src/css/base/_base.scss
src/css/components/_alert.scss
src/index.js
src/js/Alert.js
src/js/Controllers/Controller.js
src/js/Controllers/RpcFactory.js
src/js/Controllers/UIController.js
src/js/actions.js
src/js/reducers.js

Jira tasks:
[SDL-0189] As a Generic HMI, I want to be able to modify reset period [Generic HMI] (partly, only for Alert)
[SDL-0189] As a Generic HMI, I want to be able to reset the timeout for any request [Generic HMI] (partly, only for Alert)
Ready for review
Box for Reset period editor (under the main window)
Box for resetting time with timer on Alert pop-up; fuction to reset time for Alert pop-up using value from Reset period editor
TODO:
Speak functionality inside Alert rps
Checkboxes for choosing Alert or Speak for resetting timeout

[SDL-0189] Generic HMI onResetTimeout for Alert

---

src/css/components/_h-scroll-menu.scss
src/js/Controllers/UIController.js
src/js/HScrollMenu.js

Jira task:
[SDL-0189] As a Generic HMI, I want to be able to reset the timeout for PerformInteraction RPC [Generic HMI] 
Ready for review
Box for resetting time with timer on PerformInteraction pop-up; 
fuction to reset time for PerformInteraction pop-up using value from Reset period editor

 [SDL-0189] Generic HMI onResetTimeout for Perform Interaction rpc

---

src/js/Controllers/UIController.js

Get reset period value from input for alert, subtlealert, scrollablemessage

SDL-0189 Restructuring OnResetTimeout

---

src/js/Controllers/Controller.js
src/js/Controllers/RpcFactory.js
src/js/Controllers/UIController.js
src/js/actions.js
src/js/containers/Buttons.js

OnButtonSubscription deleted
SubscribeButton added - please check for further actions
Tasks:
[SDL-0192] GenericHMI Remove OnButtonSubscription notification
[SDL-0192] [Generic HMI] As a Generic HMI I want to be able to process SubscribeButton RPC (in process)

[SDL-0192] Button subscription generic

---

src/js/Controllers/UIController.js
src/js/actions.js

Added unsubscribe button functionality
TASK;
[SDL-0192] [Generic HMI] As a Generic HMI I want to be able to process UnsubscribeButton RPC

[SDL-0192] Unsubscribe button generic HMI

---

src/js/containers/Buttons.js

Fixed unsubscribeButton for Custom Button

[SDL-0192] Fixed Custom Button unsubscription

---

src/js/Alert.js
src/js/Controllers/UIController.js

[Things to note: Pull Requests **must** fix an issue. Discussion about the feature / bug takes place in the issue, discussion of the implementation takes place in the PR. Please also see the [Contributing Guide](./CONTRIBUTING.md) for information on branch naming and the CLA, and the [SmartDeviceLink GitHub Best Practices](https://d83tozu1c8tt6.cloudfront.net/media/resources/SDL_GitHub_BestPractices.pdf) document for more information on how to enter a pull request. Please create the PR as a draft until it is ready for review. Once this PR is ready for review, please request one from @JackLivio and mark the PR as ready for review.
Delete the above section when you've read it.]
Fixes #[issue number]
[List of tests performed against Core and behaviors verified]
Core version / branch / commit …

Remove unused code

---

src/js/Controllers/TTSController.js

According to comment in review (method parameter in onResetTimeout for speak case)

Fixed params of onResetTimeout for speak case

---

src/js/Controllers/TTSController.js

Manual testing
Fixed response sending for TTS.Speak request

SDL-0189 Fixed response sending for TTS.Speak request

---

src/css/components/_h-scroll-menu.scss
src/js/Controllers/UIController.js
src/js/HScrollMenu.js

Removed reset timeout functionality for PerformInteraction
Removed const RESPONSE_CORRELATION_MS in timeout of PerformInteraction

Removed reset timeout functionality for PerformInteraction

---

src/css/base/_themes.scss
src/css/components/_alert.scss
src/js/Alert.js
src/js/Controllers/TTSController.js
src/js/Controllers/UIController.js
src/js/actions.js
src/js/reducers.js

According to review
Fixed speak in TTSController

SDL-0189 Fix for TTSController by review

---

src/index.js
src/js/Alert.js
src/js/Controllers/TTSController.js
src/js/Controllers/UIController.js
src/js/ScrollableMessageButtons.js
src/js/Slider.js
src/js/actions.js
src/js/reducers.js

Transferred resetTimeout to state called system

Transferred resetTimeout to state called system

---

src/js/Alert.js
src/js/Controllers/RpcFactory.js
src/js/Controllers/TTSController.js
src/js/Controllers/UIController.js
src/js/actions.js
src/js/reducers.js

Manual testing
Core version / branch [feature/restructuring_OnResetTimeout](https://github.com/LuxoftSDL/sdl_core/tree/feature/restructuring_OnResetTimeout) / hash [d63e933cdc34983469a34785d249b01853b3dc51](https://github.com/LuxoftSDL/sdl_core/commit/d63e933cdc34983469a34785d249b01853b3dc51) 
Proxy+Test SyncProxyTester
Answer for review comments

Answer for review comments

---

src/css/base/_themes.scss
src/css/components/_h-scroll-menu.scss
src/js/Controllers/UIController.js
src/js/ScrollableMessageButtons.js
src/js/Slider.js

Answers:
- https://github.com/smartdevicelink/generic_hmi/pull/411#discussion_r681970609
- https://github.com/smartdevicelink/generic_hmi/pull/411#discussion_r681970317
- https://github.com/smartdevicelink/generic_hmi/pull/411#discussion_r681950750
- https://github.com/smartdevicelink/generic_hmi/pull/411#discussion_r681948035
- https://github.com/smartdevicelink/generic_hmi/pull/411#discussion_r681946151

Review answers

---

src/js/Controllers/RpcFactory.js
src/js/Controllers/UIController.js
src/js/actions.js
src/js/containers/Buttons.js

Fixed according review comments about:
- GENERIC_ERROR
- inconsistent structure
- subscribedButtons checking
- semicolons

Fixes according comments from ButtonSubscription review

---

src/js/Controllers/UIController.js

Resolved error with GENERIC ERROR const

Resolved error with GENERIC ERROR const

---

src/js/Controllers/TTSController.js

Answer for review comments
Manual testing
Review file TTSController.js
Applied only necessary changes for TTSController.

SDL-0189 Applied necessary changes for TTSController.js

---

src/js/Controllers/DisplayCapabilities.js

Answer fix:
Add `buttonCapabilities` to all templates

Fix buttonCapabilities

---

src/js/Controllers/DisplayCapabilities.js

Restructure buttonCapabilities

---

src/css/base/_base.scss
src/index.js
src/js/Controllers/TTSController.js
src/js/Controllers/UIController.js
src/js/ScrollableMessageButtons.js
src/js/actions.js
src/js/reducers.js

According 7 comments in the review has been removed:
- resetPeriodSelector in index.js 
- he corresponding action and reducer
- store.getState().system.resetPeriod in ScrollableMessageButtons.js, TTSController.js and UIController.js 
- if(!text) condition for this.playNext() in TTSController.js 
and
-  restored cases for keepContext

Removed inappropriate structures and values

---

src/js/ControlBarItem.js
src/js/Templates/Shared/StaticIcon.js
src/js/containers/Buttons.js

Fixes #[[FORDTCN-12632](https://adc.luxoft.com/jira/browse/FORDTCN-12632)]
Added backgroundColor style for Static Icon

Fixed issue: HMI does not highlight soft buttons on media screen
